#!/usr/bin/env python3
"""Coroutine that takes no arguments and returns the 10 random numbers
generated by async_generator."""


from typing import List

async_gnerator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """Return the 10 random numbers generated by async_generator."""
    return [number async for number in async_gnerator()]
